<a href="https://colab.research.google.com/github/H20CH3PO2/theory-of-neural-networks/blob/main/HW/NN_HW_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Не выполнена!!!
# create max(x1, x2, x3) on NN with less then 12 neurons

In [ ]:
import numpy as np

In [ ]:
weights0 = np.array([
    [ 1, 0,-1],
    [-1, 1, 0],
    [ 0,-1, 1],
])

In [ ]:
weights1 = np.array([
    [ 1,-1, 0],
    [ 0, 1,-1],
    [-1, 0, 1]
])

In [ ]:
def y0(x):
  if (x > 0):
    return 1
  return -1

def y1(x):
  if (x > 0):
    return 1
  return 0

def y2(x):
  return x

In [ ]:
x = np.array([2, 3, 3])

In [ ]:
y0_v = np.vectorize(y0)

In [ ]:
r0 = np.sum((x * weights0.T).T, axis=0)
r0

array([-1,  0,  1])

In [ ]:
r1 = y0_v(r0)
r1

array([-1, -1,  1])

In [ ]:
r2 = np.sum((weights1.T * r1).T, axis=0)
r2

array([-2,  0,  2])

In [ ]:
y1_v = np.vectorize(y1)

In [ ]:
y1_v(r2 - np.array([0.5, 0.5, 0.5]))

array([0, 0, 1])